### ISSUE TITLE
Issues with Packaged_food

### ISSUE THREAD

**Issue by Afriqvist** [CaiganMythFang/escapefromminekov#1]
Some loot is only packaged_food which can't be used at all. Pictures attached.
![food bug 2](https://user-images.githubusercontent.com/1505761/72483083-1c0d2380-3800-11ea-84f7-df00618e2c15.png)
![food bug](https://user-images.githubusercontent.com/1505761/72483084-1c0d2380-3800-11ea-89c4-78c384ceafbb.png)

**Comment by CaiganMythFang** [comment]
Oh weird, I thought those structures had been fixed properly but not. I know how to fix it, added to the list.
