### ISSUE TITLE
Acquiring Electrical Ingot

### ISSUE THREAD

**Issue by iasazo** [CaiganMythFang/escapefromminekov#5]
Electrical Ingot has no crafting recipe and also is not available to purchase from any of the traders.  Is it expected to only be found via loot?

It is required for "The Flock - Rank II".

**Comment by CaiganMythFang** [comment]
Oh whoops, I forgot to readd this recipe. Sorry about that! 2f4a207

I'll also added ability to purchase Steel ingots and Lava Crystals to The Flock's wares. 8905543 and 7d9a7b2

**Comment by iasazo** [comment]
Awesome, I wasn't sure if I was just missing something.
