### ISSUE TITLE
Quest: "Ultimate Rank I" missing check box?

### ISSUE THREAD

**Issue by iasazo** [CaiganMythFang/escapefromminekov#6]
"The Ultimate Rank I" quest under "Bandit's Journal" does not allow the rewards to be claimed because their is nothing required to turn in.  

I assume it was intended to have the check box that other quests have.

**Comment by CaiganMythFang** [comment]
Ah, knew I forgot a few quests that needed the checkbox. Fixed for next update. 4ab9d68
